import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
    {
        "id": "1",
        "name": "Methanol, HPLC Grade",
        "brand": "Sigma-Aldrich",
        "cas_number": "67-56-1",
        "purity": "99.9%",
        "price": 45.5,
        "currency": "USD",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example.com/buy/methanol-1",
        "description": "High-purity methanol for HPLC and spectrophotometry. Add to cart for fast shipping."
    },
    {
        "id": "2",
        "name": "Methanol, Reagent Grade",
        "brand": "Thermo Fisher",
        "cas_number": "67-56-1",
        "purity": "99.5%",
        "price": 32,
        "currency": "USD",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example.com/buy/methanol-2",
        "description": "Analytical reagent grade methanol. Competitive price per unit."
    },
    {
        "id": "4",
        "name": "Ethanol, Absolute, 200 Proof",
        "brand": "Alfa Aesar",
        "cas_number": "64-17-5",
        "purity": "99.5%+",
        "price": 120,
        "currency": "USD",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example.com/buy/ethanol",
        "description": "Pure ethanol for scientific research. Order now."
    },
    {
        "id": "100",
        "name": "Acetic Acid Glacial, 99.8% (AR)",
        "brand": "TCI Chemicals India",
        "cas_number": "64-19-7",
        "purity": "99.8% (AR)",
        "price": 4959,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/0",
        "description": "Verified Acetic Acid Glacial from TCI Chemicals India. Tested for 99.8% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "101",
        "name": "Acetone, 99.5% (HPLC)",
        "brand": "TCI Chemicals India",
        "cas_number": "67-64-1",
        "purity": "99.5% (HPLC)",
        "price": 3029,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/1",
        "description": "Verified Acetone from TCI Chemicals India. Tested for 99.5% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "102",
        "name": "Acetonitrile, 99.9% (GC)",
        "brand": "Thermo Fisher India",
        "cas_number": "75-05-8",
        "purity": "99.9% (GC)",
        "price": 4891,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/2",
        "description": "Verified Acetonitrile from Thermo Fisher India. Tested for 99.9% (GC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "103",
        "name": "Benzene, 99.7% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "71-43-2",
        "purity": "99.7% (AR)",
        "price": 3910,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/3",
        "description": "Verified Benzene from CDH Fine Chemicals. Tested for 99.7% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "104",
        "name": "Chloroform, 99.0% (Pharma)",
        "brand": "Loba Chemie",
        "cas_number": "67-66-3",
        "purity": "99.0% (Pharma)",
        "price": 2384,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/4",
        "description": "Verified Chloroform from Loba Chemie. Tested for 99.0% (Pharma) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "105",
        "name": "Dichloromethane (DCM), 99.9% (HPLC)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "75-09-2",
        "purity": "99.9% (HPLC)",
        "price": 225,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/5",
        "description": "Verified Dichloromethane (DCM) from CDH Fine Chemicals. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "106",
        "name": "Dimethyl Sulfoxide (DMSO), 99.5%",
        "brand": "Thermo Fisher India",
        "cas_number": "67-68-5",
        "purity": "99.5%",
        "price": 1010,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/6",
        "description": "Verified Dimethyl Sulfoxide (DMSO) from Thermo Fisher India. Tested for 99.5% purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "107",
        "name": "Dimethylformamide (DMF), 99.8% (ACS)",
        "brand": "TCI Chemicals India",
        "cas_number": "68-12-2",
        "purity": "99.8% (ACS)",
        "price": 2529,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/7",
        "description": "Verified Dimethylformamide (DMF) from TCI Chemicals India. Tested for 99.8% (ACS) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "108",
        "name": "Ethanol, 99.9% (Absolute)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "64-17-5",
        "purity": "99.9% (Absolute)",
        "price": 988,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/8",
        "description": "Verified Ethanol from SRL (Sisco Research Laboratories). Tested for 99.9% (Absolute) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "109",
        "name": "Ethyl Acetate, 99.5% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "141-78-6",
        "purity": "99.5% (AR)",
        "price": 4101,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/9",
        "description": "Verified Ethyl Acetate from SRL (Sisco Research Laboratories). Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "110",
        "name": "Hexane, 99% (n-Hexane)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "110-54-3",
        "purity": "99% (n-Hexane)",
        "price": 3835,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/10",
        "description": "Verified Hexane from SRL (Sisco Research Laboratories). Tested for 99% (n-Hexane) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "111",
        "name": "Methanol, 99.9% (HPLC)",
        "brand": "Thermo Fisher India",
        "cas_number": "67-56-1",
        "purity": "99.9% (HPLC)",
        "price": 2222,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/11",
        "description": "Verified Methanol from Thermo Fisher India. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "112",
        "name": "Tetrahydrofuran (THF), 99.8% (HPLC)",
        "brand": "Loba Chemie",
        "cas_number": "109-99-9",
        "purity": "99.8% (HPLC)",
        "price": 4275,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/12",
        "description": "Verified Tetrahydrofuran (THF) from Loba Chemie. Tested for 99.8% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "113",
        "name": "Toluene, 99.5% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "108-88-3",
        "purity": "99.5% (AR)",
        "price": 852,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/13",
        "description": "Verified Toluene from SRL (Sisco Research Laboratories). Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "114",
        "name": "Xylene, 99% (Mixed isomers)",
        "brand": "Thermo Fisher India",
        "cas_number": "1330-20-7",
        "purity": "99% (Mixed isomers)",
        "price": 3020,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/14",
        "description": "Verified Xylene from Thermo Fisher India. Tested for 99% (Mixed isomers) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "115",
        "name": "Pyridine, 99.5% (AR)",
        "brand": "Loba Chemie",
        "cas_number": "110-86-1",
        "purity": "99.5% (AR)",
        "price": 1172,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/15",
        "description": "Verified Pyridine from Loba Chemie. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "116",
        "name": "Phenol, 99% (Pharma Grade)",
        "brand": "Loba Chemie",
        "cas_number": "108-95-2",
        "purity": "99% (Pharma Grade)",
        "price": 4165,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/16",
        "description": "Verified Phenol from Loba Chemie. Tested for 99% (Pharma Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "117",
        "name": "Aniline, 99.5% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "62-53-3",
        "purity": "99.5% (AR)",
        "price": 4330,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/17",
        "description": "Verified Aniline from Thermo Fisher India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "118",
        "name": "Acrylamide, 99.9% (Biology Grade)",
        "brand": "Thermo Fisher India",
        "cas_number": "79-06-1",
        "purity": "99.9% (Biology Grade)",
        "price": 4123,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/18",
        "description": "Verified Acrylamide from Thermo Fisher India. Tested for 99.9% (Biology Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "119",
        "name": "Ammonium Acetate, 98% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "631-61-8",
        "purity": "98% (AR)",
        "price": 4054,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/19",
        "description": "Verified Ammonium Acetate from Thermo Fisher India. Tested for 98% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "120",
        "name": "Acetic Acid Glacial, 99.8% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "64-19-7",
        "purity": "99.8% (AR)",
        "price": 3895,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/20",
        "description": "Verified Acetic Acid Glacial from SRL (Sisco Research Laboratories). Tested for 99.8% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "121",
        "name": "Acetone, 99.5% (HPLC)",
        "brand": "Loba Chemie",
        "cas_number": "67-64-1",
        "purity": "99.5% (HPLC)",
        "price": 2163,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/21",
        "description": "Verified Acetone from Loba Chemie. Tested for 99.5% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "122",
        "name": "Acetonitrile, 99.9% (GC)",
        "brand": "Thermo Fisher India",
        "cas_number": "75-05-8",
        "purity": "99.9% (GC)",
        "price": 3968,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/22",
        "description": "Verified Acetonitrile from Thermo Fisher India. Tested for 99.9% (GC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "123",
        "name": "Benzene, 99.7% (AR)",
        "brand": "TCI Chemicals India",
        "cas_number": "71-43-2",
        "purity": "99.7% (AR)",
        "price": 1506,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/23",
        "description": "Verified Benzene from TCI Chemicals India. Tested for 99.7% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "124",
        "name": "Chloroform, 99.0% (Pharma)",
        "brand": "Thermo Fisher India",
        "cas_number": "67-66-3",
        "purity": "99.0% (Pharma)",
        "price": 2858,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/24",
        "description": "Verified Chloroform from Thermo Fisher India. Tested for 99.0% (Pharma) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "125",
        "name": "Dichloromethane (DCM), 99.9% (HPLC)",
        "brand": "Thermo Fisher India",
        "cas_number": "75-09-2",
        "purity": "99.9% (HPLC)",
        "price": 4044,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/25",
        "description": "Verified Dichloromethane (DCM) from Thermo Fisher India. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "126",
        "name": "Dimethyl Sulfoxide (DMSO), 99.5%",
        "brand": "CDH Fine Chemicals",
        "cas_number": "67-68-5",
        "purity": "99.5%",
        "price": 2645,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/26",
        "description": "Verified Dimethyl Sulfoxide (DMSO) from CDH Fine Chemicals. Tested for 99.5% purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "127",
        "name": "Dimethylformamide (DMF), 99.8% (ACS)",
        "brand": "Loba Chemie",
        "cas_number": "68-12-2",
        "purity": "99.8% (ACS)",
        "price": 3029,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/27",
        "description": "Verified Dimethylformamide (DMF) from Loba Chemie. Tested for 99.8% (ACS) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "128",
        "name": "Ethanol, 99.9% (Absolute)",
        "brand": "Loba Chemie",
        "cas_number": "64-17-5",
        "purity": "99.9% (Absolute)",
        "price": 1216,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/28",
        "description": "Verified Ethanol from Loba Chemie. Tested for 99.9% (Absolute) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "129",
        "name": "Ethyl Acetate, 99.5% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "141-78-6",
        "purity": "99.5% (AR)",
        "price": 3799,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/29",
        "description": "Verified Ethyl Acetate from SRL (Sisco Research Laboratories). Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "130",
        "name": "Hexane, 99% (n-Hexane)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "110-54-3",
        "purity": "99% (n-Hexane)",
        "price": 489,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/30",
        "description": "Verified Hexane from CDH Fine Chemicals. Tested for 99% (n-Hexane) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "131",
        "name": "Methanol, 99.9% (HPLC)",
        "brand": "Loba Chemie",
        "cas_number": "67-56-1",
        "purity": "99.9% (HPLC)",
        "price": 2279,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/31",
        "description": "Verified Methanol from Loba Chemie. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "132",
        "name": "Tetrahydrofuran (THF), 99.8% (HPLC)",
        "brand": "TCI Chemicals India",
        "cas_number": "109-99-9",
        "purity": "99.8% (HPLC)",
        "price": 4296,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/32",
        "description": "Verified Tetrahydrofuran (THF) from TCI Chemicals India. Tested for 99.8% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "133",
        "name": "Toluene, 99.5% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "108-88-3",
        "purity": "99.5% (AR)",
        "price": 3799,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/33",
        "description": "Verified Toluene from CDH Fine Chemicals. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "134",
        "name": "Xylene, 99% (Mixed isomers)",
        "brand": "Thermo Fisher India",
        "cas_number": "1330-20-7",
        "purity": "99% (Mixed isomers)",
        "price": 4448,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/34",
        "description": "Verified Xylene from Thermo Fisher India. Tested for 99% (Mixed isomers) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "135",
        "name": "Pyridine, 99.5% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "110-86-1",
        "purity": "99.5% (AR)",
        "price": 1790,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/35",
        "description": "Verified Pyridine from Thermo Fisher India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "136",
        "name": "Phenol, 99% (Pharma Grade)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "108-95-2",
        "purity": "99% (Pharma Grade)",
        "price": 1403,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/36",
        "description": "Verified Phenol from SRL (Sisco Research Laboratories). Tested for 99% (Pharma Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "137",
        "name": "Aniline, 99.5% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "62-53-3",
        "purity": "99.5% (AR)",
        "price": 3365,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/37",
        "description": "Verified Aniline from CDH Fine Chemicals. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "138",
        "name": "Acrylamide, 99.9% (Biology Grade)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "79-06-1",
        "purity": "99.9% (Biology Grade)",
        "price": 5118,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/38",
        "description": "Verified Acrylamide from CDH Fine Chemicals. Tested for 99.9% (Biology Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "139",
        "name": "Ammonium Acetate, 98% (AR)",
        "brand": "Loba Chemie",
        "cas_number": "631-61-8",
        "purity": "98% (AR)",
        "price": 2131,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/39",
        "description": "Verified Ammonium Acetate from Loba Chemie. Tested for 98% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "140",
        "name": "Acetic Acid Glacial, 99.8% (AR)",
        "brand": "Loba Chemie",
        "cas_number": "64-19-7",
        "purity": "99.8% (AR)",
        "price": 1909,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/40",
        "description": "Verified Acetic Acid Glacial from Loba Chemie. Tested for 99.8% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "141",
        "name": "Acetone, 99.5% (HPLC)",
        "brand": "Loba Chemie",
        "cas_number": "67-64-1",
        "purity": "99.5% (HPLC)",
        "price": 3620,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/41",
        "description": "Verified Acetone from Loba Chemie. Tested for 99.5% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "142",
        "name": "Acetonitrile, 99.9% (GC)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "75-05-8",
        "purity": "99.9% (GC)",
        "price": 3293,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/42",
        "description": "Verified Acetonitrile from SRL (Sisco Research Laboratories). Tested for 99.9% (GC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "143",
        "name": "Benzene, 99.7% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "71-43-2",
        "purity": "99.7% (AR)",
        "price": 2696,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/43",
        "description": "Verified Benzene from Thermo Fisher India. Tested for 99.7% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "144",
        "name": "Chloroform, 99.0% (Pharma)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "67-66-3",
        "purity": "99.0% (Pharma)",
        "price": 1061,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/44",
        "description": "Verified Chloroform from SRL (Sisco Research Laboratories). Tested for 99.0% (Pharma) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "145",
        "name": "Dichloromethane (DCM), 99.9% (HPLC)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "75-09-2",
        "purity": "99.9% (HPLC)",
        "price": 1617,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/45",
        "description": "Verified Dichloromethane (DCM) from CDH Fine Chemicals. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "146",
        "name": "Dimethyl Sulfoxide (DMSO), 99.5%",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "67-68-5",
        "purity": "99.5%",
        "price": 1276,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/46",
        "description": "Verified Dimethyl Sulfoxide (DMSO) from SRL (Sisco Research Laboratories). Tested for 99.5% purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "147",
        "name": "Dimethylformamide (DMF), 99.8% (ACS)",
        "brand": "TCI Chemicals India",
        "cas_number": "68-12-2",
        "purity": "99.8% (ACS)",
        "price": 2982,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/47",
        "description": "Verified Dimethylformamide (DMF) from TCI Chemicals India. Tested for 99.8% (ACS) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "148",
        "name": "Ethanol, 99.9% (Absolute)",
        "brand": "Loba Chemie",
        "cas_number": "64-17-5",
        "purity": "99.9% (Absolute)",
        "price": 4783,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/48",
        "description": "Verified Ethanol from Loba Chemie. Tested for 99.9% (Absolute) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "149",
        "name": "Ethyl Acetate, 99.5% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "141-78-6",
        "purity": "99.5% (AR)",
        "price": 2393,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/49",
        "description": "Verified Ethyl Acetate from Thermo Fisher India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "150",
        "name": "Hexane, 99% (n-Hexane)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "110-54-3",
        "purity": "99% (n-Hexane)",
        "price": 3360,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/50",
        "description": "Verified Hexane from SRL (Sisco Research Laboratories). Tested for 99% (n-Hexane) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "151",
        "name": "Methanol, 99.9% (HPLC)",
        "brand": "TCI Chemicals India",
        "cas_number": "67-56-1",
        "purity": "99.9% (HPLC)",
        "price": 4958,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/51",
        "description": "Verified Methanol from TCI Chemicals India. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "152",
        "name": "Tetrahydrofuran (THF), 99.8% (HPLC)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "109-99-9",
        "purity": "99.8% (HPLC)",
        "price": 3945,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/52",
        "description": "Verified Tetrahydrofuran (THF) from SRL (Sisco Research Laboratories). Tested for 99.8% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "153",
        "name": "Toluene, 99.5% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "108-88-3",
        "purity": "99.5% (AR)",
        "price": 1903,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/53",
        "description": "Verified Toluene from Thermo Fisher India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "154",
        "name": "Xylene, 99% (Mixed isomers)",
        "brand": "Thermo Fisher India",
        "cas_number": "1330-20-7",
        "purity": "99% (Mixed isomers)",
        "price": 4963,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/54",
        "description": "Verified Xylene from Thermo Fisher India. Tested for 99% (Mixed isomers) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "155",
        "name": "Pyridine, 99.5% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "110-86-1",
        "purity": "99.5% (AR)",
        "price": 3256,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/55",
        "description": "Verified Pyridine from Thermo Fisher India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "156",
        "name": "Phenol, 99% (Pharma Grade)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "108-95-2",
        "purity": "99% (Pharma Grade)",
        "price": 4554,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/56",
        "description": "Verified Phenol from SRL (Sisco Research Laboratories). Tested for 99% (Pharma Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "157",
        "name": "Aniline, 99.5% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "62-53-3",
        "purity": "99.5% (AR)",
        "price": 2957,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/57",
        "description": "Verified Aniline from SRL (Sisco Research Laboratories). Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "158",
        "name": "Acrylamide, 99.9% (Biology Grade)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "79-06-1",
        "purity": "99.9% (Biology Grade)",
        "price": 3723,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/58",
        "description": "Verified Acrylamide from SRL (Sisco Research Laboratories). Tested for 99.9% (Biology Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "159",
        "name": "Ammonium Acetate, 98% (AR)",
        "brand": "Loba Chemie",
        "cas_number": "631-61-8",
        "purity": "98% (AR)",
        "price": 4132,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/59",
        "description": "Verified Ammonium Acetate from Loba Chemie. Tested for 98% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "160",
        "name": "Acetic Acid Glacial, 99.8% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "64-19-7",
        "purity": "99.8% (AR)",
        "price": 2225,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/60",
        "description": "Verified Acetic Acid Glacial from CDH Fine Chemicals. Tested for 99.8% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "161",
        "name": "Acetone, 99.5% (HPLC)",
        "brand": "Loba Chemie",
        "cas_number": "67-64-1",
        "purity": "99.5% (HPLC)",
        "price": 2600,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/61",
        "description": "Verified Acetone from Loba Chemie. Tested for 99.5% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "162",
        "name": "Acetonitrile, 99.9% (GC)",
        "brand": "Loba Chemie",
        "cas_number": "75-05-8",
        "purity": "99.9% (GC)",
        "price": 3452,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/62",
        "description": "Verified Acetonitrile from Loba Chemie. Tested for 99.9% (GC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "163",
        "name": "Benzene, 99.7% (AR)",
        "brand": "TCI Chemicals India",
        "cas_number": "71-43-2",
        "purity": "99.7% (AR)",
        "price": 380,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/63",
        "description": "Verified Benzene from TCI Chemicals India. Tested for 99.7% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "164",
        "name": "Chloroform, 99.0% (Pharma)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "67-66-3",
        "purity": "99.0% (Pharma)",
        "price": 2992,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/64",
        "description": "Verified Chloroform from SRL (Sisco Research Laboratories). Tested for 99.0% (Pharma) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "165",
        "name": "Dichloromethane (DCM), 99.9% (HPLC)",
        "brand": "Thermo Fisher India",
        "cas_number": "75-09-2",
        "purity": "99.9% (HPLC)",
        "price": 3561,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/65",
        "description": "Verified Dichloromethane (DCM) from Thermo Fisher India. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "166",
        "name": "Dimethyl Sulfoxide (DMSO), 99.5%",
        "brand": "Thermo Fisher India",
        "cas_number": "67-68-5",
        "purity": "99.5%",
        "price": 1253,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/66",
        "description": "Verified Dimethyl Sulfoxide (DMSO) from Thermo Fisher India. Tested for 99.5% purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "167",
        "name": "Dimethylformamide (DMF), 99.8% (ACS)",
        "brand": "Thermo Fisher India",
        "cas_number": "68-12-2",
        "purity": "99.8% (ACS)",
        "price": 1481,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/67",
        "description": "Verified Dimethylformamide (DMF) from Thermo Fisher India. Tested for 99.8% (ACS) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "168",
        "name": "Ethanol, 99.9% (Absolute)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "64-17-5",
        "purity": "99.9% (Absolute)",
        "price": 4910,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/68",
        "description": "Verified Ethanol from SRL (Sisco Research Laboratories). Tested for 99.9% (Absolute) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "169",
        "name": "Ethyl Acetate, 99.5% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "141-78-6",
        "purity": "99.5% (AR)",
        "price": 2754,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/69",
        "description": "Verified Ethyl Acetate from SRL (Sisco Research Laboratories). Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "170",
        "name": "Hexane, 99% (n-Hexane)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "110-54-3",
        "purity": "99% (n-Hexane)",
        "price": 1286,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/70",
        "description": "Verified Hexane from SRL (Sisco Research Laboratories). Tested for 99% (n-Hexane) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "171",
        "name": "Methanol, 99.9% (HPLC)",
        "brand": "TCI Chemicals India",
        "cas_number": "67-56-1",
        "purity": "99.9% (HPLC)",
        "price": 439,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/71",
        "description": "Verified Methanol from TCI Chemicals India. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "172",
        "name": "Tetrahydrofuran (THF), 99.8% (HPLC)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "109-99-9",
        "purity": "99.8% (HPLC)",
        "price": 2783,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/72",
        "description": "Verified Tetrahydrofuran (THF) from SRL (Sisco Research Laboratories). Tested for 99.8% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "173",
        "name": "Toluene, 99.5% (AR)",
        "brand": "Thermo Fisher India",
        "cas_number": "108-88-3",
        "purity": "99.5% (AR)",
        "price": 2929,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/73",
        "description": "Verified Toluene from Thermo Fisher India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "174",
        "name": "Xylene, 99% (Mixed isomers)",
        "brand": "TCI Chemicals India",
        "cas_number": "1330-20-7",
        "purity": "99% (Mixed isomers)",
        "price": 4721,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/74",
        "description": "Verified Xylene from TCI Chemicals India. Tested for 99% (Mixed isomers) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "175",
        "name": "Pyridine, 99.5% (AR)",
        "brand": "TCI Chemicals India",
        "cas_number": "110-86-1",
        "purity": "99.5% (AR)",
        "price": 4381,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/75",
        "description": "Verified Pyridine from TCI Chemicals India. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "176",
        "name": "Phenol, 99% (Pharma Grade)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "108-95-2",
        "purity": "99% (Pharma Grade)",
        "price": 3064,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/76",
        "description": "Verified Phenol from SRL (Sisco Research Laboratories). Tested for 99% (Pharma Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "177",
        "name": "Aniline, 99.5% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "62-53-3",
        "purity": "99.5% (AR)",
        "price": 5176,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/77",
        "description": "Verified Aniline from SRL (Sisco Research Laboratories). Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "178",
        "name": "Acrylamide, 99.9% (Biology Grade)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "79-06-1",
        "purity": "99.9% (Biology Grade)",
        "price": 3135,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/78",
        "description": "Verified Acrylamide from CDH Fine Chemicals. Tested for 99.9% (Biology Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "179",
        "name": "Ammonium Acetate, 98% (AR)",
        "brand": "TCI Chemicals India",
        "cas_number": "631-61-8",
        "purity": "98% (AR)",
        "price": 3062,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/79",
        "description": "Verified Ammonium Acetate from TCI Chemicals India. Tested for 98% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "180",
        "name": "Acetic Acid Glacial, 99.8% (AR)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "64-19-7",
        "purity": "99.8% (AR)",
        "price": 1866,
        "currency": "INR",
        "unit": "L",
        "stock_status": "out_of_stock",
        "vendor_url": "https://example-vendor.in/product/80",
        "description": "Verified Acetic Acid Glacial from SRL (Sisco Research Laboratories). Tested for 99.8% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "181",
        "name": "Acetone, 99.5% (HPLC)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "67-64-1",
        "purity": "99.5% (HPLC)",
        "price": 2129,
        "currency": "INR",
        "unit": "g",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/81",
        "description": "Verified Acetone from SRL (Sisco Research Laboratories). Tested for 99.5% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "182",
        "name": "Acetonitrile, 99.9% (GC)",
        "brand": "Thermo Fisher India",
        "cas_number": "75-05-8",
        "purity": "99.9% (GC)",
        "price": 4853,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/82",
        "description": "Verified Acetonitrile from Thermo Fisher India. Tested for 99.9% (GC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "183",
        "name": "Benzene, 99.7% (AR)",
        "brand": "TCI Chemicals India",
        "cas_number": "71-43-2",
        "purity": "99.7% (AR)",
        "price": 3129,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/83",
        "description": "Verified Benzene from TCI Chemicals India. Tested for 99.7% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "184",
        "name": "Chloroform, 99.0% (Pharma)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "67-66-3",
        "purity": "99.0% (Pharma)",
        "price": 4502,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/84",
        "description": "Verified Chloroform from CDH Fine Chemicals. Tested for 99.0% (Pharma) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "185",
        "name": "Dichloromethane (DCM), 99.9% (HPLC)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "75-09-2",
        "purity": "99.9% (HPLC)",
        "price": 4850,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/85",
        "description": "Verified Dichloromethane (DCM) from CDH Fine Chemicals. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "186",
        "name": "Dimethyl Sulfoxide (DMSO), 99.5%",
        "brand": "CDH Fine Chemicals",
        "cas_number": "67-68-5",
        "purity": "99.5%",
        "price": 2429,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/86",
        "description": "Verified Dimethyl Sulfoxide (DMSO) from CDH Fine Chemicals. Tested for 99.5% purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "187",
        "name": "Dimethylformamide (DMF), 99.8% (ACS)",
        "brand": "SRL (Sisco Research Laboratories)",
        "cas_number": "68-12-2",
        "purity": "99.8% (ACS)",
        "price": 1293,
        "currency": "INR",
        "unit": "mg",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/87",
        "description": "Verified Dimethylformamide (DMF) from SRL (Sisco Research Laboratories). Tested for 99.8% (ACS) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "188",
        "name": "Ethanol, 99.9% (Absolute)",
        "brand": "Loba Chemie",
        "cas_number": "64-17-5",
        "purity": "99.9% (Absolute)",
        "price": 3267,
        "currency": "INR",
        "unit": "g",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/88",
        "description": "Verified Ethanol from Loba Chemie. Tested for 99.9% (Absolute) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "189",
        "name": "Ethyl Acetate, 99.5% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "141-78-6",
        "purity": "99.5% (AR)",
        "price": 3630,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/89",
        "description": "Verified Ethyl Acetate from CDH Fine Chemicals. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "190",
        "name": "Hexane, 99% (n-Hexane)",
        "brand": "Loba Chemie",
        "cas_number": "110-54-3",
        "purity": "99% (n-Hexane)",
        "price": 4580,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/90",
        "description": "Verified Hexane from Loba Chemie. Tested for 99% (n-Hexane) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "191",
        "name": "Methanol, 99.9% (HPLC)",
        "brand": "TCI Chemicals India",
        "cas_number": "67-56-1",
        "purity": "99.9% (HPLC)",
        "price": 3347,
        "currency": "INR",
        "unit": "L",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/91",
        "description": "Verified Methanol from TCI Chemicals India. Tested for 99.9% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "192",
        "name": "Tetrahydrofuran (THF), 99.8% (HPLC)",
        "brand": "Thermo Fisher India",
        "cas_number": "109-99-9",
        "purity": "99.8% (HPLC)",
        "price": 3794,
        "currency": "INR",
        "unit": "L",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/92",
        "description": "Verified Tetrahydrofuran (THF) from Thermo Fisher India. Tested for 99.8% (HPLC) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "193",
        "name": "Toluene, 99.5% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "108-88-3",
        "purity": "99.5% (AR)",
        "price": 2588,
        "currency": "INR",
        "unit": "g",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/93",
        "description": "Verified Toluene from CDH Fine Chemicals. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "194",
        "name": "Xylene, 99% (Mixed isomers)",
        "brand": "TCI Chemicals India",
        "cas_number": "1330-20-7",
        "purity": "99% (Mixed isomers)",
        "price": 3131,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/94",
        "description": "Verified Xylene from TCI Chemicals India. Tested for 99% (Mixed isomers) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "195",
        "name": "Pyridine, 99.5% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "110-86-1",
        "purity": "99.5% (AR)",
        "price": 1581,
        "currency": "INR",
        "unit": "ml",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/95",
        "description": "Verified Pyridine from CDH Fine Chemicals. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "196",
        "name": "Phenol, 99% (Pharma Grade)",
        "brand": "Loba Chemie",
        "cas_number": "108-95-2",
        "purity": "99% (Pharma Grade)",
        "price": 3415,
        "currency": "INR",
        "unit": "L",
        "stock_status": "out_of_stock",
        "vendor_url": "https://example-vendor.in/product/96",
        "description": "Verified Phenol from Loba Chemie. Tested for 99% (Pharma Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "197",
        "name": "Aniline, 99.5% (AR)",
        "brand": "Loba Chemie",
        "cas_number": "62-53-3",
        "purity": "99.5% (AR)",
        "price": 2726,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/97",
        "description": "Verified Aniline from Loba Chemie. Tested for 99.5% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "198",
        "name": "Acrylamide, 99.9% (Biology Grade)",
        "brand": "Thermo Fisher India",
        "cas_number": "79-06-1",
        "purity": "99.9% (Biology Grade)",
        "price": 2164,
        "currency": "INR",
        "unit": "g",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/98",
        "description": "Verified Acrylamide from Thermo Fisher India. Tested for 99.9% (Biology Grade) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "199",
        "name": "Ammonium Acetate, 98% (AR)",
        "brand": "CDH Fine Chemicals",
        "cas_number": "631-61-8",
        "purity": "98% (AR)",
        "price": 2154,
        "currency": "INR",
        "unit": "kg",
        "stock_status": "preorder",
        "vendor_url": "https://example-vendor.in/product/99",
        "description": "Verified Ammonium Acetate from CDH Fine Chemicals. Tested for 98% (AR) purity. Compliant with international organic synthesis protocols."
    },
    {
        "id": "200",
        "name": "Organic Lavender Soap, 100g",
        "category": "Soap",
        "brand": "Nature's Essence",
        "price": 150,
        "currency": "INR",
        "unit": "piece",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/soap-1",
        "description": "Handmade organic lavender soap. Soothing and free of harsh chemicals."
    },
    {
        "id": "201",
        "name": "Activated Charcoal Soap",
        "category": "Soap",
        "brand": "Pure Earth",
        "price": 120,
        "currency": "INR",
        "unit": "piece",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/soap-2",
        "description": "Deep cleansing activated charcoal soap. Helps remove impurities."
    },
    {
        "id": "202",
        "name": "Neem & Aloe Vera Organic Soap",
        "category": "Soap",
        "brand": "Ayurvedic Care",
        "price": 95,
        "currency": "INR",
        "unit": "piece",
        "stock_status": "in_stock",
        "vendor_url": "https://example-vendor.in/product/soap-3",
        "description": "Natural soap combining the antibacterial properties of Neem and the soothing effect of Aloe Vera."
    }
];
